services:
  backend:
    container_name: ToDoApp
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - 80:8000
    environment:
      - SECRET_KEY=test
      - DEBUG=True